"""
cross_checksum.py -- Fingerprinted cross-checksum (fpcc) construction.

The fpcc is generated by the client at dispersal time and distributed to all
servers alongside their respective fragment.  It encodes both a hash commitment
(h_i = SHA-256(d_i) for each fragment) and fingerprints for the first m
fragments (phi_j = fp(r, d_j) for j in [0, m)).

Structure (Definition 3.2 from the paper):
    fpcc = {
        "hashes":       [h_0, h_1, ..., h_{n-1}],   # hex strings
        "fingerprints": [phi_0, phi_1, ..., phi_{m-1}],  # int (GF256 values)
        "r":            <int>,                        # oracle output (GF256)
        "n":            <int>,
        "m":            <int>,
    }

The value of r is stored for reference/debugging but is always recomputed from
the hashes before any verification step to prevent tampering.
"""

from __future__ import annotations
import json
from dataclasses import dataclass

from ..fingerprint.field import GF256
from ..fingerprint.fingerprint import fingerprint, random_point
from ..erasure.encoder import Fragment
from .oracle import RandomOracle


@dataclass
class FingerprintedCrossChecksum:
    """The fpcc data structure distributed to all servers at dispersal time.

    Attributes:
        hashes (list[bytes]):        SHA-256 digest of each fragment, in index order.
        fingerprints (list[GF256]):  fp(r, d_j) for j in [0, m), in index order.
        r (GF256):                   The evaluation point derived from the hashes.
        n (int):                     Total number of fragments.
        m (int):                     Reconstruction threshold.
    """

    hashes: list[bytes]
    fingerprints: list[GF256]
    r: GF256
    n: int
    m: int

    @classmethod
    def generate(cls, fragments: list[Fragment]) -> FingerprintedCrossChecksum:
        """Build an fpcc from a complete set of freshly encoded fragments.

        Args:
            fragments: All n Fragment objects in index order (as returned by
                       erasure.encode).

        Returns:
            A FingerprintedCrossChecksum ready for distribution.

        Raises:
            ValueError: If `fragments` is empty or not sorted by index.
        """

        if not fragments:
            raise ValueError("fragments cannot be empty")
        for i, f in enumerate(fragments):
            if f.index != i:
                raise ValueError(f"fragments must be in index order with no gaps. Fragment at position {i} has index {f.index}.")

        hashes = [RandomOracle.hash_fragment(f.data) for f in fragments]
        r = RandomOracle.derive(hashes)
        n = len(fragments)
        m = fragments[0].threshold_m
        fingerprints = [fingerprint(r, fragments[j].data) for j in range(0, m)]

        return FingerprintedCrossChecksum(hashes, fingerprints, r, n, m)
        

    # ------------------------------------------------------------------
    # Serialization
    # ------------------------------------------------------------------

    def to_json(self) -> str:
        """Serialize the fpcc to a JSON string for storage/transmission.

        Returns:
            A JSON string encoding all fields.
        """

        hashes_json = [h.hex() for h in self.hashes]
        fingerprints_json = [fp.value for fp in self.fingerprints]
        r_json = self.r.value

        json_dict = {
            "hashes": hashes_json,
            "fingerprints": fingerprints_json,
            "r": r_json,
            "n": self.n,
            "m": self.m
        }

        return json.dumps(json_dict)

    @classmethod
    def from_json(cls, json_str: str) -> FingerprintedCrossChecksum:
        """Deserialize an fpcc from its JSON representation.

        Args:
            json_str: A JSON string produced by to_json().

        Returns:
            A FingerprintedCrossChecksum instance.
        """
        json_dict = json.loads(json_str)
        hashes = [bytes.fromhex(h) for h in json_dict["hashes"]]
        fingerprints = [GF256(fp) for fp in json_dict["fingerprints"]]
        r = GF256(json_dict["r"])
        n = json_dict["n"]
        m = json_dict["m"]

        return cls(hashes, fingerprints, r, n, m)

    def digest(self) -> str:
        """Return a hex digest of the canonical JSON representation.

        Used as the fpcc_digest field in FragmentRecord to allow re-verification.

        Returns:
            A hex string (SHA-256 of the canonical JSON).
        """
        return RandomOracle.hash_fragment(self.to_json().encode()).hex()
